version: 2
updates:
  # 👇 Manage Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"  # location of pom.xml
    schedule:
      interval: "daily"
      time: "03:30"   # 9:00 AM IST = 03:30 UTC
      timezone: "UTC"
    open-pull-requests-limit: 10

    # 👇 Auto-merge minor and patch updates
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # 👇 Manage GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:30"
      timezone: "UTC"
    open-pull-requests-limit: 10

    # 👇 Auto-merge minor and patch updates for Actions too
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
