name: Daily 5pm IST CI

on:
  schedule:
    - cron: '30 11 * * 1-6'   # 11:30 UTC = 17:00 IST, Mon(1)–Sat(6)
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Install Chrome
        run: choco install googlechrome --no-progress

      - name: Build and run tests
        run: mvn -B -ntp clean verify
