name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout your repository
      - uses: actions/checkout@v4

      # ✅ Set up JDK (change version if needed)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # ✅ Build and run tests with Maven
      - name: Build and run tests
        run: mvn -B -ntp clean verify

      # ✅ Auto-approve Dependabot PRs (optional)
      - name: Auto-approve Dependabot PRs
        if: github.actor == 'dependabot[bot]'
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # ✅ Auto-merge Dependabot PRs (optional)
      - name: Auto-merge Dependabot PRs
        if: github.actor == 'dependabot[bot]'
        uses: peter-evans/merge-auto@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
