name: Java CI with Maven

on:
  push:
    paths:
      - 'src/test/java/org/example/SignUp.java'
  pull_request:
    paths:
      - 'src/test/java/org/example/SignUp.java'

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DEPENDENCY_SUBMISSION_ENABLED: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml
