name: SignUp class

on:
  push:
    paths:
      - 'src/test/java/org/example/SignUp.java'
  pull_request:
    paths:
      - 'src/test/java/org/example/SignUp.java'
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
    
permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Install Chrome
        run: choco install googlechrome --no-progress

      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v3.1.1
        with:
          step: restore

      - name: Build and run tests
        run: mvn -B -ntp clean verify

      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v3.1.1
        with:
          step: save  
