name: signup class with workflow dispatch

on:
  push:
    paths:
      - 'src/test/java/org/example/SignUp.java'
  pull_request:
    paths:
      - 'src/test/java/org/example/SignUp.java'
  schedule:
    - cron: '0 12 * * *'   # 12:00 UTC
  workflow_dispatch:
    inputs:
      mavenProfile:
        description: 'Maven profile to run'
        required: false
        type: choice
        options: [web, android, ios, unit-test]
        default: web
      remoteURL:
        description: 'Selenium Grid URL'
        required: false
        type: string
        default: 'http://localhost:4444/wd/hub'

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Install Chrome
        run: choco install googlechrome --no-progress

      - name: Resolve inputs with defaults
        id: vars
        run: |
          echo "PROFILE=${{ inputs.mavenProfile || 'web' }}" >> "$GITHUB_ENV"
          echo "REMOTE_URL=${{ inputs.remoteURL || 'http://localhost:4444/wd/hub' }}" >> "$GITHUB_ENV"
        # For schedule/push, inputs are null; || applies safe defaults [web:248].

      - name: Build and run tests
        run: mvn -B -ntp clean verify -P "$PROFILE" -Dselenium.remoteUrl="$REMOTE_URL"
